using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using F2.Repository.Configurations.Converters;
using F2.Repository.Extensions;

namespace F2.Repository.Demo.Models.Configurations
{
    public class BookEntityConfiguration : IEntityTypeConfiguration<Book>
    {
        public void Configure(EntityTypeBuilder<Book> builder)
        {
            builder.UseAutoGeneratedId();
            builder.UseTimestampedProperty();

            builder.HasMany(s => s.Authors).WithMany(s => s.Books);

            builder.Property(p => p.ArrivedAt).HasConversion<DateTimeOffsetToUtcConverter>();
        }
    }
}