# docker-compose up -d

# debug database
# launch Update-Database from vsconsole to migrate the database

version: "3.7"

services:


  # MAIN APPLICATION DATABASE
  database_default:
    image: postgres:14-alpine
    ports:
      - 1440:5432
    environment:
      POSTGRES_USER: Library
      POSTGRES_PASSWORD: develop
    volumes:
      - database_application_data:/var/lib/postgresql/data



volumes:
  database_application_data:
    