using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oibi.Repository.Extensions;

namespace Oibi.Repository.Demo.Models.Configurations
{
	public class BookEntityConfiguration : IEntityTypeConfiguration<Book>
	{
		public void Configure(EntityTypeBuilder<Book> builder)
		{
			builder.UseAutoGeneratedId();
			builder.UseTimestampedProperty();

			builder.HasMany(s => s.Authors).WithMany(s => s.Books);
		}
	}
}