# https://github.com/NuGet/setup-nuget
name: NuGet Generation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet
    steps:
      - uses: actions/checkout@master
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_APIKEY }}
      - uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 7.0.*

      - name: Build solution and generate NuGet package
        run: |
          cd Oibi.Repository
          dotnet pack -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -c Release -o \out

      - name: Push generated package to the registry
        run: nuget push \out\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate
